### ISSUE TITLE
suggestions for working with embedded WebExtensions?

### ISSUE THREAD

**Issue by gregglind** [Standard8/example-webextension#65]
Some issues:
- addon signing
- testing bootstrap.js stuff?

**Comment by Standard8** [comment]
I must have missed this when first filed. There's an [example-addon-repo](https://github.com/mozilla/example-addon-repo/) that we created a while back for system add-ons. This has a embedded WebExtension structure by default.

Since embedded WebExtensions will only be supported for system add-ons after 57, I think that is enough and we don't need to add it to this repo.
